DROP TABLE IF EXISTS `acompl_stat_iso`;
CREATE TABLE IF NOT EXISTS acompl_stat_iso (
  kod               CHAR (5),
  nazev             VARCHAR(100) NOT NULL,
  mpz               CHAR(5),
  PRIMARY KEY (kod)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;

CREATE INDEX acompl_stat_iso_idx ON acompl_stat_iso (kod);

INSERT INTO `acompl_stat_iso` (`kod`, `nazev`, `mpz`) VALUES
('?', 'Nezjištěno', '?'),
('AD', 'Andorra', 'AND'),
('AE', 'Spojené arabské emiráty', 'UAE'),
('AF', 'Afghánistán', 'AFG'),
('AG', 'Antigua a Barbuda', 'AG'),
('AI', 'Anguilla', NULL),
('AL', 'Albánie', 'AL'),
('AM', 'Arménie', 'ARM'),
('AO', 'Angola', 'ANG'),
('AQ', 'Antarktida', NULL),
('AR', 'Argentina', 'RA'),
('AS', 'Americká Samoa', NULL),
('AT', 'Rakousko', 'A'),
('AU', 'Austrálie', 'AUS'),
('AW', 'Aruba', NULL),
('AX', 'Alandy', NULL),
('AZ', 'Ázerbájdžán', 'AZ'),
('BA', 'Bosna a Hercegovina', 'BIH'),
('BB', 'Barbados', 'BDS'),
('BD', 'Bangladéš', 'BD'),
('BE', 'Belgie', 'B'),
('BF', 'Burkina Faso', 'BF'),
('BG', 'Bulharsko', 'BG'),
('BH', 'Bahrajn', 'BRN'),
('BI', 'Burundi', 'BU'),
('BJ', 'Benin', NULL),
('BL', 'Svatý Bartoloměj', NULL),
('BM', 'Bermudy', NULL),
('BN', 'Brunej', 'BRU'),
('BO', 'Bolívie', 'BOL'),
('BQ', 'Bonaire, Svatý Eustach a Saba', NULL),
('BR', 'Brazílie', 'BR'),
('BS', 'Bahamy', 'BS'),
('BT', 'Bhútán', 'BHT'),
('BV', 'Bouvetův ostrov', NULL),
('BW', 'Botswana', 'BW'),
('BY', 'Bělorusko', 'BY'),
('BZ', 'Belize', 'BH'),
('CA', 'Kanada', 'CDN'),
('CC', 'Kokosové ostrovy', NULL),
('CD', 'Demokratická republika Kongo', 'ZRE'),
('CF', 'Středoafrická republika', 'RCA'),
('CG', 'Kongo', 'RCB'),
('CI', 'Pobřeží slonoviny', 'CI'),
('CK', 'Cookovy ostrovy', NULL),
('CL', 'Chile', 'RCH'),
('CM', 'Kamerun', 'CAM'),
('CN', 'Čína', NULL),
('CO', 'Kolumbie', 'CO'),
('CR', 'Kostarika', 'CR'),
('CU', 'Kuba', 'C'),
('CV', 'Kapverdy', 'CV'),
('CW', 'Curaçao', NULL),
('CX', 'Vánoční ostrov', NULL),
('CY', 'Kypr', 'CY'),
('CZ', 'Česká republika', 'CZ'),
('DE', 'Německo', 'D'),
('DJ', 'Džibutsko', 'DJI'),
('DK', 'Dánsko', 'DK'),
('DM', 'Dominika', 'WD'),
('DO', 'Dominikánská republika', 'DOM'),
('DZ', 'Alžírsko', 'DZ'),
('EC', 'Ekvádor', 'EC'),
('EE', 'Estonsko', 'EST'),
('EG', 'Egypt', 'ET'),
('EH', 'Západní Sahara', NULL),
('ER', 'Eritrea', 'ER'),
('ES', 'Španělsko', 'E'),
('ET', 'Etiopie', 'ETH'),
('FI', 'Finsko', 'FIN'),
('FJ', 'Fidži', 'FJI'),
('FK', 'Falklandy (Malvíny)', NULL),
('FM', 'Mikronésie', 'FSM'),
('FO', 'Faerské ostrovy', 'FO'),
('FR', 'Francie', 'F'),
('GA', 'Gabon', 'G'),
('GB', 'Spojené království Velké Británie a Severního Irska', 'GB'),
('GD', 'Grenada', 'WG'),
('GE', 'Gruzie', 'GE'),
('GF', 'Francouzská Guyana', NULL),
('GG', 'Guernsey', 'GBG'),
('GH', 'Ghana', 'GH'),
('GI', 'Gibraltar', 'GBZ'),
('GL', 'Grónsko', 'KN'),
('GM', 'Gambie', 'WAG'),
('GN', 'Guinea', 'RG'),
('GP', 'Guadeloupe', NULL),
('GQ', 'Rovníková Guinea', 'GQ'),
('GR', 'Řecko', 'GR'),
('GS', 'Jižní Georgie a Jižní Sandwichovy ostrovy', NULL),
('GT', 'Guatemala', 'GCA'),
('GU', 'Guam', NULL),
('GW', 'Guinea-Bissau', 'GW'),
('GY', 'Guyana', 'GUY'),
('HK', 'Hongkong', 'HK'),
('HM', 'Heardův ostrov a McDonaldovy ostrovy', NULL),
('HN', 'Honduras', 'HN'),
('HR', 'Chorvatsko', 'HR'),
('HT', 'Haiti', 'RH'),
('HU', 'Maďarsko', 'H'),
('CH', 'Švýcarsko', 'CH'),
('ID', 'Indonésie', 'RI'),
('IE', 'Irsko', 'IRL'),
('IL', 'Izrael', 'IL'),
('IM', 'Ostrov Man', NULL),
('IN', 'Indie', 'IND'),
('IO', 'Britské indickooceánské území', NULL),
('IQ', 'Irák', 'IRQ'),
('IR', 'Írán', 'IR'),
('IS', 'Island', 'IS'),
('IT', 'Itálie', 'I'),
('JE', 'Jersey', 'GBJ'),
('JM', 'Jamajka', 'JA'),
('JO', 'Jordánsko', 'HKJ'),
('JP', 'Japonsko', 'J'),
('KE', 'Keňa', 'EAK'),
('KG', 'Kyrgyzstán', 'KS'),
('KH', 'Kambodža', 'K'),
('KI', 'Kiribati', 'KIR'),
('KM', 'Komory', NULL),
('KN', 'Svatý Kryštof a Nevis', 'KAN'),
('KP', 'Severní Korea', NULL),
('KR', 'Jižní Korea', 'ROK'),
('KW', 'Kuvajt', 'KWT'),
('KY', 'Kajmanské ostrovy', NULL),
('KZ', 'Kazachstán', 'KZ'),
('LA', 'Laos', 'LAO'),
('LB', 'Libanon', 'RL'),
('LC', 'Svatá Lucie', 'WL'),
('LI', 'Lichtenštejnsko', 'FL'),
('LK', 'Srí Lanka', NULL),
('LR', 'Libérie', 'LB'),
('LS', 'Lesotho', 'LS'),
('LT', 'Litva', 'LT'),
('LU', 'Lucembursko', 'L'),
('LV', 'Lotyšsko', 'LV'),
('LY', 'Libye', 'LAR'),
('MA', 'Maroko', 'MA'),
('MC', 'Monako', 'MC'),
('MD', 'Moldavsko', 'MD'),
('ME', 'Černá Hora', 'MNE'),
('MF', 'Svatý Martin (francouzská část)', NULL),
('MG', 'Madagaskar', 'RM'),
('MH', 'Marshallovy ostrovy', 'MH'),
('MK', 'Severní Makedonie', NULL),
('ML', 'Mali', 'RMM'),
('MM', 'Myanmar', 'MYA'),
('MN', 'Mongolsko', 'MGL'),
('MO', 'Macao', NULL),
('MP', 'Severní Mariany', NULL),
('MQ', 'Martinik', NULL),
('MR', 'Mauritánie', 'RIM'),
('MS', 'Montserrat', NULL),
('MT', 'Malta', 'M'),
('MU', 'Mauricius', 'MS'),
('MV', 'Maledivy', 'MV'),
('MW', 'Malawi', 'MW'),
('MX', 'Mexiko', 'MEX'),
('MY', 'Malajsie', 'MAL'),
('MZ', 'Mosambik', 'MOC'),
('NA', 'Namibie', 'NAM'),
('NC', 'Nová Kaledonie', NULL),
('NE', 'Niger', 'RN'),
('NF', 'Norfolk', NULL),
('NG', 'Nigérie', 'WAN'),
('NI', 'Nikaragua', 'NIC'),
('NL', 'Nizozemsko', 'NL'),
('NO', 'Norsko', 'N'),
('NP', 'Nepál', 'NEP'),
('NR', 'Nauru', 'NAU'),
('NU', 'Niue', NULL),
('NZ', 'Nový Zéland', 'NZ'),
('OM', 'Omán', 'OM'),
('PA', 'Panama', 'PA'),
('PE', 'Peru', 'PE'),
('PF', 'Francouzská Polynésie', NULL),
('PG', 'Papua Nová Guinea', NULL),
('PH', 'Filipíny', 'RP'),
('PK', 'Pákistán', 'PK'),
('PL', 'Polsko', 'PL'),
('PM', 'Saint Pierre a Miquelon', NULL),
('PN', 'Pitcairnovy ostrovy', NULL),
('PR', 'Portoriko', NULL),
('PS', 'Palestinská autonomie', NULL),
('PT', 'Portugalsko', 'P'),
('PW', 'Palau', 'PAL'),
('PY', 'Paraguay', 'PY'),
('QA', 'Katar', 'Q'),
('RE', 'Réunion', NULL),
('RO', 'Rumunsko', 'RO'),
('RS', 'Srbsko', 'SRB'),
('RU', 'Rusko', 'RUS'),
('RW', 'Rwanda', 'RWA'),
('SA', 'Saúdská Arábie', 'KSA'),
('SB', 'Šalomounovy ostrovy', NULL),
('SC', 'Seychely', 'SY'),
('SD', 'Súdán', 'SUD'),
('SE', 'Švédsko', 'S'),
('SG', 'Singapur', 'SGP'),
('SH', 'Svatá Helena, Ascension a Tristan da Cunha', NULL),
('SI', 'Slovinsko', 'SLO'),
('SJ', 'Špicberky a Jan Mayen', NULL),
('SK', 'Slovensko', 'SK'),
('SL', 'Sierra Leone', 'SLE'),
('SM', 'San Marino', 'RSM'),
('SN', 'Senegal', 'SN'),
('SO', 'Somálsko', 'SO'),
('SR', 'Surinam', 'SME'),
('SS', 'Jižní Súdán', NULL),
('ST', 'Svatý Tomáš a Princův ostrov', 'STP'),
('SV', 'Salvador', 'ES'),
('SX', 'Svatý Martin (nizozemská část)', NULL),
('SY', 'Sýrie', 'SYR'),
('SZ', 'Svazijsko', 'SD'),
('TC', 'Turks a Caicos', NULL),
('TD', 'Čad', 'TCH'),
('TF', 'Francouzská jižní a antarktická území', NULL),
('TG', 'Togo', 'TG'),
('TH', 'Thajsko', 'T'),
('TJ', 'Tádžikistán', 'TJ'),
('TK', 'Tokelau', NULL),
('TL', 'Východní Timor', 'TL'),
('TM', 'Turkmenistán', 'TM'),
('TN', 'Tunisko', 'TN'),
('TO', 'Tonga', 'TO'),
('TR', 'Turecko', 'TR'),
('TT', 'Trinidad a Tobago', 'TT'),
('TV', 'Tuvalu', 'TUV'),
('TW', 'Tchaj-wan', NULL),
('TZ', 'Tanzanie', 'EAT'),
('UA', 'Ukrajina', 'UA'),
('UG', 'Uganda', 'EAU'),
('UM', 'Menší odlehlé ostrovy USA', NULL),
('US', 'Spojené státy americké', 'USA'),
('UY', 'Uruguay', 'UY'),
('UZ', 'Uzbekistán', 'UZ'),
('VA', 'Vatikán', 'SCV'),
('VC', 'Svatý Vincenc a Grenadiny', 'WV'),
('VE', 'Venezuela', 'YV'),
('VG', 'Britské Panenské ostrovy', 'BVI'),
('VI', 'Americké Panenské ostrovy', NULL),
('VN', 'Vietnam', 'VN'),
('VU', 'Vanuatu', 'VU'),
('WF', 'Wallis a Futuna', NULL),
('WS', 'Samoa', 'WS'),
('YE', 'Jemen', 'YAR'),
('YT', 'Mayotte', NULL),
('ZA', 'Jihoafrická republika', 'ZA'),
('ZM', 'Zambie', 'Z'),
('ZW', 'Zimbabwe', 'ZW');




